bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/controller/dto/request/ClassRoomDto.java
bdink/src/main/java/com/app/bdink/classroom/controller/dto/request/PriceDto.java
bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomResponse.java
bdink/src/main/java/com/app/bdink/classroom/domain/Career.java
bdink/src/main/java/com/app/bdink/classroom/domain/ChapterSummary.java
bdink/src/main/java/com/app/bdink/classroom/domain/PriceDetail.java
bdink/src/main/java/com/app/bdink/classroom/entity/ClassRoom.java
bdink/src/main/java/com/app/bdink/classroom/entity/Instructor.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
bdink/src/main/java/com/app/bdink/lecture/controller/InstructorController.java
bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
bdink/src/main/java/com/app/bdink/lecture/controller/dto/InstructorDto.java
bdink/src/main/java/com/app/bdink/lecture/entity/Chapter.java
bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
bdink/src/main/java/com/app/bdink/lecture/repository/ChapterRepository.java
bdink/src/main/java/com/app/bdink/lecture/repository/InstructorRepository.java
bdink/src/main/java/com/app/bdink/lecture/service/ChapterService.java
bdink/src/main/java/com/app/bdink/lecture/service/InstructorService.java
bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
bdink/src/main/java/com/app/bdink/member/entity/Member.java
bdink/src/test/java/com/app/bdink/classroom/domain/PriceDetailTest.java

feature/#2(ClassRoomController): 컨트롤러로 테스트

---

bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/domain/Career.java
bdink/src/main/java/com/app/bdink/classroom/entity/Instructor.java
bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
bdink/src/main/java/com/app/bdink/lecture/controller/InstructorController.java
bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
bdink/src/main/java/com/app/bdink/lecture/controller/dto/request/UpdateInstructorDto.java
bdink/src/main/java/com/app/bdink/lecture/controller/dto/response/InstructorInfoDto.java
bdink/src/main/java/com/app/bdink/lecture/repository/InstructorRepository.java
bdink/src/main/java/com/app/bdink/lecture/service/InstructorService.java
bdink/src/main/java/com/app/bdink/member/entity/Member.java
bdink/src/main/java/com/app/bdink/news/controller/NewsController.java
bdink/src/main/java/com/app/bdink/news/controller/dto/request/NewsReqDto.java
bdink/src/main/java/com/app/bdink/news/controller/dto/response/NewsResDto.java
bdink/src/main/java/com/app/bdink/news/entity/News.java
bdink/src/main/java/com/app/bdink/news/repository/NewsRepository.java
bdink/src/main/java/com/app/bdink/news/service/NewsService.java

feature(swagger): swagger 관련 설명 추가

---

bdink/build.gradle
bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
bdink/src/main/java/com/app/bdink/global/jwt/JwtFilter.java
bdink/src/main/java/com/app/bdink/global/oauth2/kakao/controller/KakaoLoginController.java
bdink/src/main/java/com/app/bdink/global/oauth2/kakao/dto/KakaoTokenResDto.java
bdink/src/main/java/com/app/bdink/global/oauth2/kakao/info/KakaoUserInfo.java
bdink/src/main/java/com/app/bdink/global/oauth2/kakao/service/KakaoService.java
bdink/src/main/java/com/app/bdink/global/token/Token.java
bdink/src/main/java/com/app/bdink/global/token/TokenProvider.java
bdink/src/main/java/com/app/bdink/member/entity/Member.java
bdink/src/main/java/com/app/bdink/member/entity/Role.java
bdink/src/main/java/com/app/bdink/member/repository/MemberRepository.java

카카오 소셜로그인 작성했습니다.
규림언니와 SecurityConfig, Member 클래스 충돌났으니 확인 부탁드려용~

feature/#5(KakaoService): Kakao OAuth2 작성

---

bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java

hotfix(securityConfig)/#17: swagger 핫픽스설정

---

bdink/build.gradle
bdink/src/main/java/com/app/bdink/external/coolsms/controller/SmsController.java
bdink/src/main/java/com/app/bdink/member/entity/Member.java

Fix(SmsController): 버그 수정

---

bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/controller/dto/request/ClassRoomDto.java
bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomResponse.java
bdink/src/main/java/com/app/bdink/classroom/entity/ClassRoom.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
bdink/src/main/java/com/app/bdink/external/aws/service/S3Service.java

클래스룸 썸네일 이미지 넣는 로직을 추가했습니다!
@eunxeum 이미지 datasource 관련 버그 제보해주셔서 감사합니다 ㅎㅎ

feature/#26(ClassRoom): 클래스룸 이미지 썸네일 로직 추가

---

bdink/src/main/java/com/app/bdink/member/controller/MemberController.java
bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberPhoneUpdateRequestDto.java
bdink/src/main/java/com/app/bdink/member/entity/Member.java
bdink/src/main/java/com/app/bdink/member/service/MemberService.java

feature/#33(Member): 전화번호 필드 추가

---

bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomDetailResponse.java
bdink/src/main/java/com/app/bdink/classroom/repository/BookmarkRepository.java
bdink/src/main/java/com/app/bdink/classroom/service/BookmarkService.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java

- 북마크 개수 확인 추가
- 클래스 디테일 페이지 조회 api 작성

feature/#66(ClassRoom): 클래스 디테일 페이지 조회 api 작성

---

bdink/.gitignore
bdink/src/main/java/com/app/bdink/global/exception/Error.java
bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/global/oauth2/AuthService.java
bdink/src/main/java/com/app/bdink/global/oauth2/SocialAuthController.java
bdink/src/main/java/com/app/bdink/global/oauth2/apple/request/Parts.java
bdink/src/main/java/com/app/bdink/global/oauth2/apple/request/RevokeParts.java
bdink/src/main/java/com/app/bdink/global/oauth2/apple/response/TokenResponse.java
bdink/src/main/java/com/app/bdink/global/oauth2/apple/service/AppleSignInService.java
bdink/src/main/java/com/app/bdink/global/oauth2/apple/verify/PublicKeyGenerator.java
bdink/src/main/java/com/app/bdink/global/oauth2/kakao/service/KakaoSignInService.java
bdink/src/main/java/com/app/bdink/member/entity/Member.java
bdink/src/main/java/com/app/bdink/member/service/MemberService.java

회원 관련 로직변경이 있을 수 있어서 member.delete에서 이상은 있을 수 있으나 통신과정 제대로 되는지 확인하기 위해 푸시. 다른 로직에는 영향 가는 부분없습니다.

[Feature/#82] 소셜 로그인 및 회원탈퇴 구현.

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomProgressResponse.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
bdink/src/main/java/com/app/bdink/sugang/entity/Sugang.java
bdink/src/main/java/com/app/bdink/sugang/repository/SugangRepository.java

feature/#94(Sugang): 진행률 관련 로직 작성

---

bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/InstructorDto.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/request/UpdateInstructorDto.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/response/InstructorInfoDto.java
bdink/src/main/java/com/app/bdink/instructor/adapter/out/persistence/entity/Instructor.java
bdink/src/main/java/com/app/bdink/instructor/domain/InstructorDomain.java
bdink/src/main/java/com/app/bdink/instructor/mapper/InstructorMapper.java
bdink/src/main/java/com/app/bdink/instructor/service/InstructorService.java

feature/#111(Instructor): 강사 홍보 기능 구현

---

bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/schedule/controller/ScheduleController.java
bdink/src/main/java/com/app/bdink/schedule/domain/CompetitionType.java
bdink/src/main/java/com/app/bdink/schedule/entity/Schedule.java

```json
{
"statusCode": 201,
"message": "스케줄 생성 성공",
"data": {
"id": 17
}
}
```
```json
{
"statusCode": 200,
"message": "날짜별 스케줄 조회 성공",
"data": [
{
"title": "흠냐대회",
"date": "2025-10-10",
"scheduleType": "COMPETITION",
"competionImage": null,
"competitionType": "NABBA"
},
{
"title": "흠냐대회",
"date": "2025-10-10",
"scheduleType": "COMPETITION",
"competionImage": "https://어쩌구.cloudfront.net/image/e5c7cec6-2b7d-4406-b58d-409b3bed778f.jpg",
"competitionType": "NABBA"
}
]
}
```

fix/#126(Schedule): 스케줄 썸네일 로직 수정

---

bdink/src/main/java/com/app/bdink/external/coolsms/service/SmsService.java
bdink/src/main/java/com/app/bdink/global/exception/Error.java
bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/oauth2/controller/SocialAuthController.java

refactor/#147(SocialAuthController): 문자 인증 번호 체크 api 분기처리

---

bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java

hotfix/#155(KollusService): kollus 업로드 콜백 로직 수정

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/AllClassRoomResponse.java

[Modify] Career의 강사 조회 api 강사 프로필이미지 추가

---

bdink/src/main/java/com/app/bdink/global/exception/Error.java
bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/youtube/controller/YoutubeController.java
bdink/src/main/java/com/app/bdink/youtube/domain/YoutubeInfoDto.java
bdink/src/main/java/com/app/bdink/youtube/entity/Youtube.java
bdink/src/main/java/com/app/bdink/youtube/repository/YoutubeRepository.java
bdink/src/main/java/com/app/bdink/youtube/service/YoutubeService.java

[Feature] 유튜브 비디오 CRUD

---

bdink/src/main/java/com/app/bdink/youtube/controller/YoutubeController.java
bdink/src/main/java/com/app/bdink/youtube/domain/YoutubeInfoDto.java
bdink/src/main/java/com/app/bdink/youtube/domain/YoutubeType.java
bdink/src/main/java/com/app/bdink/youtube/entity/Youtube.java
bdink/src/main/java/com/app/bdink/youtube/repository/YoutubeRepository.java
bdink/src/main/java/com/app/bdink/youtube/service/YoutubeService.java

[Feature] YoutubeVideo 유튜브 타입 조회 API

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
bdink/src/main/java/com/app/bdink/classroom/port/in/ClassRoomUseCase.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/PlayRequestDTO.java
bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
bdink/src/main/java/com/app/bdink/member/service/MemberService.java
bdink/src/main/java/com/app/bdink/sugang/controller/SugangController.java
bdink/src/main/java/com/app/bdink/sugang/controller/dto/SugangStatus.java
bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangClassRoomInfo.java
bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangInfoDto.java
bdink/src/main/java/com/app/bdink/sugang/entity/Sugang.java
bdink/src/main/java/com/app/bdink/sugang/repository/SugangRepository.java
bdink/src/main/java/com/app/bdink/sugang/service/SugangService.java
bdink/src/main/java/com/app/bdink/youtube/service/YoutubeService.java

[Feature] Kollus 진행률 콜백 api 구현, 수강 엔티티를 통한 진행률 기능 개발, 클래스룸 디테일 페이지 결제 관련 데이터 추가

---

bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/sugang/controller/SugangController.java

modify/#188(SugangController) 수강신청 클래스룸 목록 조회 api 응답값 변경

---

bdink/src/main/java/com/app/bdink/review/adapter/in/controller/dto/response/ReviewResponse.java
bdink/src/main/java/com/app/bdink/review/service/ReviewService.java

리뷰 조회 API 추가 파라미터 요구사항 구현
- 본인이 작성한 리뷰인지 여부 boolean 파라미터 추가
- 리뷰 ID 파라미터 추가

[Add] 리뷰 조회 API - 본인이 작성한 리뷰인지 여부 boolean 파라미터 추가

---

bdink/src/main/java/com/app/bdink/external/coolsms/entity/PhoneVerify.java
bdink/src/main/java/com/app/bdink/external/coolsms/service/SmsService.java

[Modify] 인증번호 체크 api 3분 이상 시간 소요시 인증 되는 버그 수정

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomResponse.java
bdink/src/main/java/com/app/bdink/classroom/port/in/ClassRoomUseCase.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java

클라이언트 측 요청 사항으로 ClassRoomController의 getClassRoomInfo에서 리턴하는 Response에 isBookmarked 인스턴스를 추가하여 리턴하도록 수정했습니다.

[Add] 강의 구매 페이지에 북마크 상태를 Boolean으로 반환하는 기능 구현

---

bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/LmsRequestDTO.java
bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/PlayRequestDTO.java
bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
bdink/src/main/java/com/app/bdink/global/exception/Success.java
bdink/src/main/java/com/app/bdink/instructor/repository/InstructorRepository.java
bdink/src/main/java/com/app/bdink/mypage/controller/MyPageController.java
bdink/src/main/java/com/app/bdink/mypage/dto/response/MyPageResponse.java
bdink/src/main/java/com/app/bdink/mypage/service/MyPageService.java

- #211 
- Kollus 콘솔에서 모바일에서 play 할 경우 버딩크 서버를 호출하는 post callback API 구현
- 관련 api 주소 (get API) :  baseUrl/api/v1/mypage 
- 강사일 경우
- 강사가 아닐경우

[Feature] 콜러스 재생 콜백 api 생성, 마이페이지 api 생성

---

bdink/src/main/java/com/app/bdink/mypage/dto/response/MyPageResponse.java
bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangClassRoomInfo.java

- #233 
- Sugang all API 해당 강의 강사 이름 응답 추가
- MyPage API 닉네임 응답 추가

[Modify] Sugang all api 해당 강의 강사 이름 응답 추가, MyPage API 닉네임 응답 추가

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/AllCareerClassRoomResponse.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/CategorizedClassroomDto.java
bdink/src/main/java/com/app/bdink/classroom/port/in/ClassRoomUseCase.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java

변동 API : 클래스룸 전체 조회 API
엔드포인트 : 
- /api/v1/classroom/all
변경 내용 : 
- classroom/all api의 200 Response data의 classroomDtoByCareer에서 
classrooms 배열의 각 요소에 "isBookmarked": Boolean 필드를 추가했습니다.
추가 필드 : 
- isBookmarked (Boolean) -> Classroom All API

[Modify] 피드에 북마크 여부 프로퍼티 추가

---

bdink/src/main/java/com/app/bdink/oauth2/controller/SocialAuthController.java
bdink/src/main/java/com/app/bdink/sugang/controller/SugangController.java

- #244 
- 로그아웃 API (응답 문구 수정, data 응답 값 변경)
- 수강 API (data 응답 값 분기 처리)

[Modify] 앱단 개발 질문 관련 응답 값 수정

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
bdink/src/main/java/com/app/bdink/classroom/port/in/ClassRoomUseCase.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java

ClassRoom controller의 getClassRoomDetail에서 반환하는 ClassRoomDetailResponse에 isBookmarked(Boolean), classRoomId(Long) 프로퍼티를 추가하였습니다.

[Modify] class detail에 북마크 여부 확인 파라미터 추가

---

bdink/src/main/java/com/app/bdink/bookmark/adapter/in/controller/dto/response/BookmarkResponse.java
bdink/src/main/java/com/app/bdink/bookmark/repository/BookmarkRepository.java
bdink/src/main/java/com/app/bdink/bookmark/service/BookmarkService.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java

1. 클래스 디테일 페이지를 조회하는 API - 200 data에 classRoomId 삭제했습니다.
2. 북마크한 클래스룸을 조회하는 API - 200 data에 classRoomId을 추가했습니다.
3. 북마크를 저장하는 API - 이미 저장된 북마크를 다시 저장할 경우 400을 던지는 예외처리를 수정했습니다.

[Modify] 북마크 관련 API 수정 사항 반영

---

bdink/src/main/java/com/app/bdink/bookmark/adapter/in/controller/BookmarkController.java
bdink/src/main/java/com/app/bdink/bookmark/adapter/in/controller/dto/response/BookmarkResponse.java
bdink/src/main/java/com/app/bdink/bookmark/repository/BookmarkRepository.java
bdink/src/main/java/com/app/bdink/bookmark/service/BookmarkService.java
bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java

엔드포인트 :
/api/v1/bookmark (GET)
북마크 API 추가 데이터 요청 사항입니다.
- 썸네일
- 총 몇강인지

[Modify] 북마크 조회 API 응답 수정

---

bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java

SecurityConfig에서 version check-update api를 토큰 검증에서 제외하도록 수정했습니다!

[Modify] version check-update api 토큰 검증에서 제외

---

bdink/src/main/java/com/app/bdink/payment/toss/service/PaymentService.java

[Hotfix] WIDGET_SECRET_KEY 값 수정

---

bdink/src/main/java/com/app/bdink/classroom/repository/ClassRoomRepository.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/response/InstructorAllInfoDto.java
bdink/src/main/java/com/app/bdink/instructor/repository/InstructorRepository.java
bdink/src/main/java/com/app/bdink/instructor/service/InstructorService.java

[Feat] 모든 강사 정보 API 추가

---

bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java
bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/response/InstructorClassroomDto.java

- #322
- 서버에서 500에러가 발생해 확인해본 결과 강사에서 마케팅이미지를 가져와야하는데 member.getInstructor << 이 부분에서 null값이 생기고 거기서 마케팅이미지를 가져올 때의 에러였습니다.
- member에서 instructor를 가져오는것이 아닌 instructor에서 마케팅 이미지를 가져오는 방식으로 전환

[Hotfix] 강사별 클래스룸을 조회 API

---

bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java

- #327 
- 콜러스 MediaLink API 분기처리 (신규, 기존 생성)

[Modify] 콜러스 MediaLink API 분기처리

---

bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
bdink/src/main/java/com/app/bdink/classroom/repository/ClassRoomRepository.java
bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java

- #314 
- 임시로 promotionOf의 값이 23인 경우 CAREER  PROMOTION 분기처리

[Feature] ClassRoom Career PROMOTION과 다른 CAREER 분기처리

---

bdink/src/main/java/com/app/bdink/message/controller/AlimtalkTestController.java
bdink/src/main/java/com/app/bdink/message/controller/dto/AlimTalkRequest.java
bdink/src/main/java/com/app/bdink/message/controller/dto/AlimTalkText.java
bdink/src/main/java/com/app/bdink/message/service/KakaoAlimtalkService.java
bdink/src/main/java/com/app/bdink/message/service/KakaoAlimtalkServiceImpl.java
bdink/src/main/java/com/app/bdink/message/service/KakaoAlimtalkTokenSchedular.java

알림톡 전송 테스트를 위한 Controller를 구현했습니다. 배포 환경에서 테스트 이후 결제 로직과 연결하려 합니다.

[Feat] 알림톡 전송 API 연결

---

bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/request/ClassRoomImageCreateRequest.java
bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/request/ClassRoomImagesDto.java
bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
bdink/src/main/java/com/app/bdink/classroom/mapper/ClassRoomMapper.java
bdink/src/main/java/com/app/bdink/classroom/service/command/CreateClassRoomCommand.java

- #386 
- 클래스룸 엔티티에 새로운 필드인 프로모션, 디테일 썸네일 추가

[Feat] 클래스룸 이미지 파편화

---

bdink/src/main/java/com/app/bdink/payment/apple/service/ApplePaymentServiceImpl.java

- ApplePaymentServiceImpl getInAppPurchase 메소드 샌드박스 환경 예외처리

[Fix] ApplePaymentServiceImpl getInAppPurchase 메소드 샌드박스 환경 예외처리
